name = "Shoppable Video"
client_id = "replace-me"
application_url = "https://replace-with-your-vercel-app-url.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[auth]
redirect_urls = [
  "https://replace-with-your-vercel-app-url.vercel.app/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"

[access_scopes]
scopes = "read_products"
